### ISSUE TITLE
Support faker for custom scalars

### ISSUE THREAD

**Issue by ardeois** [ardeois/graphql-codegen-typescript-mock-data#97]
`scalars` option allows to use custom generator function from `casual`

Now we have `generateLibrary` supporting `faker`, we should allow custom generator functions from faker as well

**Comment by MH4GF** [comment]
memo:

- casual is only one level with property calls, like this: `country` => `casual["country"] // 'United Kingdom'`
  - Some generators may be function calls that specify arguments: `integer` => `integer(from = -1000, to = 1000) // 632`
- faker is a nested method chain: `faker.address.country() // 'Greece'`

---

This is what happens when you offer an interface similar to casual 🤔 : `address.country` => `faker["address"]["country"]()`
